"use client";

type StructuredAnalysisData = {
  title?: string;
  researchQuestion?: string;
  methodology?: {
    design?: string;
    data?: string;
    analysis?: string;
  };
  keyFindings?: string[];
  contributions?: string[];
  limitations?: string[];
  futureWork?: string[];
  keywords?: string[];
  shortSummary?: string;
};

export async function exportStructuredAnalysisToPdf(
  data: StructuredAnalysisData,
  articleTitle?: string,
  fileName?: string,
) {
  if (typeof window === "undefined") {
    throw new Error("PDF export is only available in the browser");
  }

  const { default: jsPDF } = await import("jspdf");

  const title = data.title ?? articleTitle ?? "Structured Analysis";
  const pdf = new jsPDF({
    orientation: "p",
    unit: "pt",
    format: "a4",
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const colors = {
    title: "#18181b",
    heading: "#27272a",
    subheading: "#3f3f46",
    text: "#52525b",
    accent: "#10b981",
    muted: "#71717a",
  };

  // Helper to add text with word wrap
  const addText = (
    text: string,
    fontSize: number,
    color: string,
    bold = false,
    indent = 0,
  ) => {
    pdf.setFontSize(fontSize);
    pdf.setTextColor(color);
    pdf.setFont("helvetica", bold ? "bold" : "normal");
    const lines = pdf.splitTextToSize(text, contentWidth - indent);
    for (const line of lines) {
      if (y + fontSize > pageHeight - margin) {
        pdf.addPage();
        y = margin;
      }
      pdf.text(line, margin + indent, y);
      y += fontSize * 1.4;
    }
  };

  const addSection = (sectionTitle: string, content: string | string[]) => {
    y += 10;
    addText(sectionTitle, 12, colors.heading, true);
    y += 4;
    if (Array.isArray(content)) {
      for (const item of content) {
        addText(`• ${item}`, 10, colors.text, false, 12);
      }
    } else {
      addText(content, 10, colors.text);
    }
  };

  // Title
  addText(title, 18, colors.title, true);
  y += 8;

  // Keywords
  if (data.keywords && data.keywords.length > 0) {
    addText(`Keywords: ${data.keywords.join(", ")}`, 9, colors.muted);
    y += 8;
  }

  // Horizontal line
  pdf.setDrawColor(200, 200, 200);
  pdf.line(margin, y, pageWidth - margin, y);
  y += 16;

  // Summary
  if (data.shortSummary) {
    addText("Summary", 12, colors.heading, true);
    y += 4;
    addText(data.shortSummary, 10, colors.text);
    y += 12;
  }

  // Research Question
  if (data.researchQuestion) {
    addSection("Research Question", data.researchQuestion);
    y += 8;
  }

  // Methodology
  if (data.methodology) {
    y += 10;
    addText("Methodology", 12, colors.heading, true);
    y += 4;
    if (data.methodology.design) {
      addText("Design", 10, colors.subheading, true, 8);
      addText(data.methodology.design, 10, colors.text, false, 8);
      y += 4;
    }
    if (data.methodology.data) {
      addText("Data", 10, colors.subheading, true, 8);
      addText(data.methodology.data, 10, colors.text, false, 8);
      y += 4;
    }
    if (data.methodology.analysis) {
      addText("Analysis", 10, colors.subheading, true, 8);
      addText(data.methodology.analysis, 10, colors.text, false, 8);
    }
    y += 8;
  }

  // Key Findings
  if (data.keyFindings && data.keyFindings.length > 0) {
    addSection("Key Findings", data.keyFindings);
    y += 8;
  }

  // Contributions
  if (data.contributions && data.contributions.length > 0) {
    addSection("Contributions", data.contributions);
    y += 8;
  }

  // Limitations
  if (data.limitations && data.limitations.length > 0) {
    addSection("Limitations", data.limitations);
    y += 8;
  }

  // Future Work
  if (data.futureWork && data.futureWork.length > 0) {
    addSection("Future Work", data.futureWork);
  }

  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(colors.muted);
    pdf.text(
      `Page ${i} of ${totalPages} • Generated by RUI`,
      pageWidth / 2,
      pageHeight - 20,
      { align: "center" },
    );
  }

  pdf.save(fileName ?? `${title}-structured-analysis.pdf`);
}
